source 'https://github.com/li125434104/XJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/wgModularization/WGModulSpecs.git'

use_frameworks!

platform :ios, '8.0'

target 'XJAuthorTestKit_Example' do
  pod 'XJAuthorTestKit', :path => '../'

  target 'XJAuthorTestKit_Tests' do
    inherit! :search_paths

    
  end
end
